FROM fedora
RUN rpm -e cpio cronie cronie-noanacron crontabs cryptsetup-libs dbus device-mapper device-mapper-libs diffutils dracut dracut-config-rescue dtc fipscheck fipscheck-lib hardlink hostname initscripts iputils kmod kmod-libs kpartx libedit openssh openssh-clients passwd procps-ng qrencode-libs rootfiles rsync sudo systemd sysvinit-tools tar tcp_wrappers-libs uboot-tools vim-minimal xz
